# Generated by Django 6.0 on 2026-05-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_discussion_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
