# Generated by Django 6.0 on 2026-05-26 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_commande_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_destinataire', models.CharField(max_length=20)),
                ('contenu', models.TextField()),
                ('statut', models.CharField(choices=[('envoyé', 'Envoyé'), ('erreur', 'Erreur'), ('en_attente', 'En attente')], default='envoyé', max_length=20)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_envois', to='shop.commande')),
            ],
            options={
                'verbose_name_plural': 'SMS',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
