"""
Django settings for projet1djan project.

Generated by 'django-admin startproject' using Django 5.2.1.
"""

from pathlib import Path
import os
import sys


# Chemin de base
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')

# Permet d'importer des apps placées dans un dossier "apps" (optionnel)
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Clé secrète (à sécuriser en production)
SECRET_KEY = 'django-insecure-fzj0)ue7%-p+f!y5t5c%!^62d9^mq!rrdk%i9naritk#n=3)17'

DEBUG = True
import os
import dj_database_url  # pour la base Render PostgreSQL

# ...

# Autoriser Render à accéder au site
ALLOWED_HOSTS = [os.environ.get('RENDER_EXTERNAL_HOSTNAME', '127.0.0.1')]

# Configuration par défaut (local SQLite)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Configuration pour Render (production)
if os.environ.get('RENDER'):
    DATABASES['default'] = dj_database_url.config(conn_max_age=600)


# Applications installées
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # Tes applications
    'accounts',  # <-- App de gestion des utilisateurs
    'shop',
]

# Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.ActiveUserMiddleware',
]

ROOT_URLCONF = 'projet1djan.urls'

# Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ os.path.join(BASE_DIR, 'shop', 'templates'),
                os.path.join(BASE_DIR, 'accounts', 'templates'),

                ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.categories_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'projet1djan.wsgi.application'

# Base de données
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Validation des mots de passe
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Langue et fuseau horaire
LANGUAGE_CODE = 'fr-FR'
TIME_ZONE = 'Europe/Paris'
USE_I18N = True
USE_TZ = True

# Fichiers statiques
STATIC_URL = 'static/'

# Clé primaire par défaut
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ✅ Activation du modèle utilisateur personnalisé
AUTH_USER_MODEL = 'accounts.CustomUser'

# Redirections login/logout
LOGIN_REDIRECT_URL = '/dashboard/'  # page après connexion réussie
LOGOUT_REDIRECT_URL = '/login/'  # page après déconnexion
LOGOUT_REDIRECT_URL = '/login/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
